### ISSUE TITLE
Bug when starting test environment

### ISSUE THREAD

**Issue by samqi** [Sinar/imap#17]
**Describe the bug**
test site `bin/instance fg` can not start and fails with various errors:
```
/home/sam/workspace/Sinar/imap/eggs/Products.CMFCore-2.7.1-py3.8.egg/Products/CMFCore/CachingPolicyManager.py:30: DeprecationWarning: IObjectMovedEvent is deprecated. Some zope.container interfaces have been mov
ed to zope.lifecycleevent.interfaces, please import form there.
  from zope.container.interfaces import IObjectMovedEvent                                                                                                                                                          
/home/sam/workspace/Sinar/imap/eggs/Products.CMFCore-2.7.1-py3.8.egg/Products/CMFCore/CMFCatalogAware.py:28: DeprecationWarning: IObjectAddedEvent is deprecated. Some zope.container interfaces have been moved to
 zope.lifecycleevent.interfaces, please import form there.                                                                                                                                                         
  from zope.container.interfaces import IObjectAddedEvent
2023-11-09 10:43:54,862 INFO    [chameleon.config:38][MainThread] directory cache: /home/sam/workspace/Sinar/imap/var/cache.
/home/sam/workspace/Sinar/imap/eggs/plone.contentrules-2.1.3-py3.8.egg/plone/contentrules/engine/interfaces.py:4: DeprecationWarning: IContained is deprecated. Some zope.container interfaces have been moved to z
ope.location.interfaces, please import form there.                                                                                                                                                                 
  from zope.container.interfaces import IContained
/home/sam/workspace/Sinar/imap/eggs/plone.app.contentrules-4.1.6-py3.8.egg/plone/app/contentrules/handlers.py:16: DeprecationWarning: IObjectRemovedEvent is deprecated. Some zope.container interfaces have been m
oved to zope.lifecycleevent.interfaces, please import form there.
  from zope.container.interfaces import IObjectRemovedEvent                                                                                                                                                        
/home/sam/workspace/Sinar/imap/eggs/pyScss-1.3.7-py3.8-linux-x86_64.egg/scss/types.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since P
ython 3.3, and in 3.10 it will stop working                                                                                                                                                                        
  from collections import Iterable    
/home/sam/workspace/Sinar/imap/eggs/pyScss-1.3.7-py3.8-linux-x86_64.egg/scss/namespace.py:172: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfulla
rgspec()             
  argspec = inspect.getargspec(function)                                                                                                                                                                           
/home/sam/workspace/Sinar/imap/eggs/pyScss-1.3.7-py3.8-linux-x86_64.egg/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''                                                                                                                                                                             
/home/sam/workspace/Sinar/imap/eggs/plone.app.drafts-1.1.3-py3.8-linux-x86_64.egg/plone/app/drafts/proxy.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc'
 is deprecated since Python 3.3, and in 3.10 it will stop working                                                                                                                                                  
  from collections import MutableMapping                                                                 
/home/sam/workspace/Sinar/imap/eggs/plone.app.standardtiles-2.5.0-py3.8.egg/plone/app/standardtiles/navigation.py:5: DeprecationWarning: isDefaultPage is deprecated. Import from Products.CMFPlone instead
  from plone.app.layout.navigation.defaultpage import isDefaultPage
/home/sam/workspace/Sinar/imap/eggs/Products.CMFDynamicViewFTI-6.0.3-py3.8.egg/Products/CMFDynamicViewFTI/interface.py:7: DeprecationWarning: import from Products.CMFDynamicViewFTI.interfaces instead
  warnings.warn(                                                                                         
2023-11-09 10:44:02,004 WARNING [z3c.autoinclude:33][MainThread] resolve('blackd') raised import error: aiohttp dependency is not installed: No module named 'aiohttp'. Please re-install black with the '[d]' extr
a install to obtain aiohttp_cors: `pip install black[d]`
/home/sam/workspace/Sinar/imap/venv/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils. 
  warnings.warn("Setuptools is replacing distutils.")
2023-11-09 10:44:02,368 WARNING [z3c.autoinclude:33][MainThread] resolve('blackd') raised import error: aiohttp dependency is not installed: No module named 'aiohttp'. Please re-install black with the '[d]' extr
a install to obtain aiohttp_cors: `pip install black[d]`
2023-11-09 10:44:03,327 WARNING [Init:86][MainThread] Class plone.app.drafts.storage.Storage has a security declaration for nonexistent method 'drafts'
Traceback (most recent call last):
  File "/home/sam/workspace/Sinar/imap/parts/instance/bin/interpreter", line 299, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
File "/home/sam/workspace/Sinar/imap/eggs/Zope-4.8.10-py3.8.egg/Zope2/Startup/serve.py", line 255, in <module>                                                                                          [0/64160]
    sys.exit(main() or 0)
  File "/home/sam/workspace/Sinar/imap/eggs/Zope-4.8.10-py3.8.egg/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/home/sam/workspace/Sinar/imap/eggs/Zope-4.8.10-py3.8.egg/Zope2/Startup/serve.py", line 189, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
  File "/home/sam/workspace/Sinar/imap/eggs/Zope-4.8.10-py3.8.egg/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/sam/workspace/Sinar/imap/eggs/PasteDeploy-3.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 248, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/sam/workspace/Sinar/imap/eggs/PasteDeploy-3.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 273, in loadobj
    return context.create()
  File "/home/sam/workspace/Sinar/imap/eggs/PasteDeploy-3.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
  File "/home/sam/workspace/Sinar/imap/eggs/PasteDeploy-3.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 200, in invoke
    app = context.app_context.create()
  File "/home/sam/workspace/Sinar/imap/eggs/PasteDeploy-3.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
  File "/home/sam/workspace/Sinar/imap/eggs/PasteDeploy-3.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 138, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/sam/workspace/Sinar/imap/eggs/PasteDeploy-3.0.1-py3.8.egg/paste/deploy/util.py", line 61, in fix_call
    val = callable(*args, **kw)
  File "/home/sam/workspace/Sinar/imap/eggs/Zope-4.8.10-py3.8.egg/Zope2/Startup/run.py", line 72, in make_wsgi_app
    starter.prepare()
  File "/home/sam/workspace/Sinar/imap/eggs/Zope-4.8.10-py3.8.egg/Zope2/Startup/starter.py", line 41, in prepare
    self.startZope()
  File "/home/sam/workspace/Sinar/imap/eggs/Zope-4.8.10-py3.8.egg/Zope2/Startup/starter.py", line 99, in startZope
    Zope2.startup_wsgi()
  File "/home/sam/workspace/Sinar/imap/eggs/Zope-4.8.10-py3.8.egg/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/home/sam/workspace/Sinar/imap/eggs/Zope-4.8.10-py3.8.egg/Zope2/App/startup.py", line 162, in startup
    notify(DatabaseOpenedWithRoot(DB))
  File "/home/sam/workspace/Sinar/imap/eggs/zope.event-4.6-py3.8.egg/zope/event/__init__.py", line 33, in notify
    subscriber(event)
  File "/home/sam/workspace/Sinar/imap/eggs/zope.component-4.6.2-py3.8.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "/home/sam/workspace/Sinar/imap/eggs/zope.component-4.6.2-py3.8.egg/zope/component/_api.py", line 134, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/sam/workspace/Sinar/imap/eggs/zope.interface-5.5.2-py3.8-linux-x86_64.egg/zope/interface/registry.py", line 448, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/sam/workspace/Sinar/imap/eggs/zope.interface-5.5.2-py3.8-linux-x86_64.egg/zope/interface/adapter.py", line 899, in subscribers
    subscription(*objects)
  File "/home/sam/workspace/Sinar/imap/eggs/plone.app.theming-4.1.8-py3.8.egg/plone/app/theming/plugins/hooks.py", line 16, in onStartup
    pluginSettings = getPluginSettings(themeDirectory, plugins)
  File "/home/sam/workspace/Sinar/imap/eggs/plone.memoize-3.0.0-py3.8.egg/plone/memoize/volatile.py", line 74, in replacement
    cached_value = cache[key] = fun(*args, **kwargs) 
  File "/home/sam/workspace/Sinar/imap/eggs/plone.app.theming-4.1.8-py3.8.egg/plone/app/theming/plugins/utils.py", line 96, in getPluginSettings
    parser.read_string(fp.read().decode())
  File "/home/sam/.pyenv/versions/3.8.18/lib/python3.8/configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "/home/sam/.pyenv/versions/3.8.18/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/home/sam/.pyenv/versions/3.8.18/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '<string>' [line  5]: option 'title' in section 'theme' already exists

```

**To Reproduce**
1. Use ubuntu 22.04.3, [install dependencies](https://github.com/Sinar/imap#ubuntu-22042-lts) & [pyenv (since default is > 3.8)](https://github.com/Sinar/imap#venv-and-buildout-environment-where-base-python-is-newer-than-38) 
2. run pyenv for venv, but use 3.8.18 as that is the latest
`~/.pyenv/versions/3.8.18/bin/python3.8 -m venv venv`
3. Upgrade pip due to warning `/home/sam/workspace/Sinar/imap/venv/bin/python3.8 -m pip install --upgrade pip`
and & Setup buildout environment
```
venv/bin/pip install setuptools==65.7.0 zc.buildout==3.0.1 wheel==0.38.4 \
plonecli
venv/bin/buildout bootstrap
```
4. Run buildout `bin/buildout -vvv`, `bin/instance fg` 
& encounter aboove error

**Expected behavior**
starts dev imap plone environment

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - Shell : /bin/bash
  - Version 5.1.16

**Comment by sitinurliza95** [comment]
I think it should be resolved with the latest commit, but if not, try editing the file `../src/imap/customizations/theme/manifest.cfg` to:

```
[theme]
title = Plone Theme: Imap theme
description = A theme for Plone 6 Classic UI
preview = preview.png
rules = 
prefix = /++theme++imap-theme
doctype = <!DOCTYPE html>

enabled-bundles =
disabled-bundles =

production-css = /++theme++imap-theme/css/theme.min.css
tinymce-content-css = /++theme++imap-theme/css/theme.min.css
production-js = /++theme++imap-theme/js/theme.min.js
```

There should only be just one `title`

**Comment by samqi** [comment]
amended and fixed `src/imap.customizations/src/imap/customizations/theme/manifest.cfg` and it works as it should
